import {
  DEFAULT_SOUND_CONFIG,
  type SoundId,
  type SoundPlaybackConfig,
} from './audio.types';
import { FactionAudioId, SoundCategory } from './audio.types';

const V = (volume: number) => volume;
const C = (cooldownMs: number) => cooldownMs;

export const SOUND_REGISTRY: Record<SoundId, SoundPlaybackConfig> = {
  'ui.click': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.3),
    category: SoundCategory.UI,
    cooldownMs: C(50),
  },
  'ui.hover': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.15),
    category: SoundCategory.UI,
    cooldownMs: C(100),
  },
  'ui.open': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.25),
    category: SoundCategory.UI,
  },
  'ui.close': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.25),
    category: SoundCategory.UI,
  },
  'ui.error': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.35),
    category: SoundCategory.UI,
    pitchMin: 0.8,
    pitchMax: 0.9,
  },
  'ui.success': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.3),
    category: SoundCategory.UI,
    pitchMin: 1.1,
    pitchMax: 1.2,
  },
  'ui.build_select': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.2),
    category: SoundCategory.UI,
  },
  'ui.faction_select': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.25),
    category: SoundCategory.UI,
  },
  'ui.wave_start': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.4),
    category: SoundCategory.UI,
  },
  'ui.wave_complete': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.35),
    category: SoundCategory.UI,
  },
  'ui.game_over': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.5),
    category: SoundCategory.UI,
    pitchMin: 0.7,
    pitchMax: 0.85,
  },
  'ui.victory': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.45),
    category: SoundCategory.UI,
  },
  'system.pause': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.25),
    category: SoundCategory.SYSTEM,
  },
  'system.unpause': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.25),
    category: SoundCategory.SYSTEM,
  },
  'system.restart': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.3),
    category: SoundCategory.SYSTEM,
  },
  'economy.gold_gain': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.25),
    category: SoundCategory.ECONOMY,
    pitchMin: 1.15,
    pitchMax: 1.25,
  },
  'economy.gold_spent': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.2),
    category: SoundCategory.ECONOMY,
    pitchMin: 0.9,
    pitchMax: 1.0,
  },
  'economy.refund': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.2),
    category: SoundCategory.ECONOMY,
  },
  'economy.life_lost': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.4),
    category: SoundCategory.ECONOMY,
    pitchMin: 0.75,
    pitchMax: 0.9,
  },
  'economy.wave_reward': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.35),
    category: SoundCategory.ECONOMY,
    pitchMin: 1.1,
    pitchMax: 1.2,
  },
  'combat.tower_attack.archer': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.28),
    category: SoundCategory.COMBAT,
    cooldownMs: C(150),
    pitchMin: 0.9,
    pitchMax: 1.1,
    factionTags: [FactionAudioId.UNDEAD, FactionAudioId.HUMAN, FactionAudioId.ELF],
  },
  'combat.tower_attack.splash': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.35),
    category: SoundCategory.COMBAT,
    cooldownMs: C(300),
    pitchMin: 0.85,
    pitchMax: 1.0,
    factionTags: [FactionAudioId.UNDEAD],
  },
  'combat.creep_hit': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.22),
    category: SoundCategory.COMBAT,
    cooldownMs: C(80),
    pitchMin: 0.95,
    pitchMax: 1.05,
  },
  'combat.creep_death.basic': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.32),
    category: SoundCategory.COMBAT,
    cooldownMs: C(100),
    pitchMin: 0.8,
    pitchMax: 1.0,
  },
  'combat.creep_death.elite': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.4),
    category: SoundCategory.COMBAT,
    cooldownMs: C(150),
    pitchMin: 0.7,
    pitchMax: 0.9,
  },
  'combat.creep_escape': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.35),
    category: SoundCategory.COMBAT,
    pitchMin: 0.8,
    pitchMax: 0.95,
  },
  'combat.invalid_build': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.3),
    category: SoundCategory.COMBAT,
    pitchMin: 0.6,
    pitchMax: 0.75,
  },
  'combat.successful_build': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.3),
    category: SoundCategory.COMBAT,
    pitchMin: 1.1,
    pitchMax: 1.2,
  },
  'combat.sell_tower': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.28),
    category: SoundCategory.COMBAT,
  },
  'ambient.map': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.15),
    category: SoundCategory.AMBIENT,
    loop: true,
  },
  'ambient.tension': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.12),
    category: SoundCategory.AMBIENT,
    loop: true,
  },
  'ambient.faction.undead': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.18),
    category: SoundCategory.AMBIENT,
    loop: true,
    factionTags: [FactionAudioId.UNDEAD],
  },
  'ambient.faction.orc': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.18),
    category: SoundCategory.AMBIENT,
    loop: true,
    factionTags: [FactionAudioId.ORC],
  },
  'ambient.faction.human': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.18),
    category: SoundCategory.AMBIENT,
    loop: true,
    factionTags: [FactionAudioId.HUMAN],
  },
  'ambient.faction.elf': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.18),
    category: SoundCategory.AMBIENT,
    loop: true,
    factionTags: [FactionAudioId.ELF],
  },
};

export const AUDIO_CONSTANTS = {
  MAX_SIMULTANEOUS_SOUNDS: 12,
  MAX_SIMULTANEOUS_SAME_CATEGORY: 6,
  DEFAULT_MASTER_VOLUME: 0.7,
  MOBILE_UNLOCK_DEBOUNCE_MS: 500,
  CLEANUP_CHECK_INTERVAL_MS: 500,
  POOL_SIZE: 8,
} as const;
