import {
  DEFAULT_SOUND_CONFIG,
  type SoundId,
  type SoundPlaybackConfig,
} from './audio.types';
import { FactionAudioId, SoundCategory } from './audio.types';

const V = (volume: number) => volume;
const C = (cooldownMs: number) => cooldownMs;

export const SOUND_REGISTRY: Record<SoundId, SoundPlaybackConfig> = {
  'ui.click': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.3),
    category: SoundCategory.UI,
    cooldownMs: C(50),
    maxDurationSec: 0.1,
  },
  'ui.hover': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.15),
    category: SoundCategory.UI,
    cooldownMs: C(100),
    maxDurationSec: 0.05,
  },
  'ui.open': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.25),
    category: SoundCategory.UI,
    maxDurationSec: 0.25,
  },
  'ui.close': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.25),
    category: SoundCategory.UI,
    maxDurationSec: 0.25,
  },
  'ui.error': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.35),
    category: SoundCategory.UI,
    pitchMin: 0.8,
    pitchMax: 0.9,
    maxDurationSec: 0.3,
  },
  'ui.success': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.3),
    category: SoundCategory.UI,
    pitchMin: 1.1,
    pitchMax: 1.2,
    maxDurationSec: 0.25,
  },
  'ui.build_select': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.2),
    category: SoundCategory.UI,
    maxDurationSec: 0.15,
  },
  'ui.faction_select': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.25),
    category: SoundCategory.UI,
    maxDurationSec: 0.2,
  },
  'ui.wave_start': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.4),
    category: SoundCategory.UI,
    maxDurationSec: 0.5,
    startOffsetSec: 0.03,
  },
  'ui.wave_complete': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.35),
    category: SoundCategory.UI,
    maxDurationSec: 0.6,
  },
  'ui.game_over': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.5),
    category: SoundCategory.UI,
    pitchMin: 0.7,
    pitchMax: 0.85,
    maxDurationSec: 1.2,
  },
  'ui.victory': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.45),
    category: SoundCategory.UI,
    maxDurationSec: 1.5,
  },
  'system.pause': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.25),
    category: SoundCategory.SYSTEM,
    maxDurationSec: 0.2,
  },
  'system.unpause': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.25),
    category: SoundCategory.SYSTEM,
    maxDurationSec: 0.2,
  },
  'system.restart': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.3),
    category: SoundCategory.SYSTEM,
    maxDurationSec: 0.3,
  },
  'economy.gold_gain': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.25),
    category: SoundCategory.ECONOMY,
    pitchMin: 1.15,
    pitchMax: 1.25,
    maxDurationSec: 0.25,
  },
  'economy.gold_spent': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.2),
    category: SoundCategory.ECONOMY,
    pitchMin: 0.9,
    pitchMax: 1.0,
    maxDurationSec: 0.2,
  },
  'economy.refund': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.2),
    category: SoundCategory.ECONOMY,
    maxDurationSec: 0.25,
  },
  'economy.life_lost': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.4),
    category: SoundCategory.ECONOMY,
    pitchMin: 0.75,
    pitchMax: 0.9,
    maxDurationSec: 0.4,
  },
  'economy.wave_reward': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.35),
    category: SoundCategory.ECONOMY,
    pitchMin: 1.1,
    pitchMax: 1.2,
    maxDurationSec: 0.5,
  },
  'combat.tower_attack.archer': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.28),
    category: SoundCategory.COMBAT,
    cooldownMs: C(40),
    pitchMin: 0.9,
    pitchMax: 1.1,
    factionTags: [FactionAudioId.UNDEAD, FactionAudioId.ORC, FactionAudioId.HUMAN, FactionAudioId.ELF],
    maxDurationSec: 0.3,
    startOffsetSec: 0.025,
  },
  'combat.tower_attack.archer.undead': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.28),
    category: SoundCategory.COMBAT,
    cooldownMs: C(40),
    pitchMin: 0.9,
    pitchMax: 1.1,
    factionTags: [FactionAudioId.UNDEAD],
  },
  'combat.tower_attack.archer.orc': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.28),
    category: SoundCategory.COMBAT,
    cooldownMs: C(40),
    pitchMin: 0.9,
    pitchMax: 1.1,
    factionTags: [FactionAudioId.ORC],
  },
  'combat.tower_attack.archer.human': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.28),
    category: SoundCategory.COMBAT,
    cooldownMs: C(40),
    pitchMin: 0.9,
    pitchMax: 1.1,
    factionTags: [FactionAudioId.HUMAN],
  },
  'combat.tower_attack.archer.elf': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.28),
    category: SoundCategory.COMBAT,
    cooldownMs: C(40),
    pitchMin: 0.9,
    pitchMax: 1.1,
    factionTags: [FactionAudioId.ELF],
  },
  'combat.tower_attack.splash': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.35),
    category: SoundCategory.COMBAT,
    cooldownMs: C(80),
    pitchMin: 0.85,
    pitchMax: 1.0,
    factionTags: [FactionAudioId.UNDEAD, FactionAudioId.ORC, FactionAudioId.HUMAN, FactionAudioId.ELF],
    maxDurationSec: 0.5,
    startOffsetSec: 0.02,
  },
  'combat.tower_attack.splash.undead': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.35),
    category: SoundCategory.COMBAT,
    cooldownMs: C(80),
    pitchMin: 0.85,
    pitchMax: 1.0,
    factionTags: [FactionAudioId.UNDEAD],
  },
  'combat.tower_attack.splash.orc': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.35),
    category: SoundCategory.COMBAT,
    cooldownMs: C(80),
    pitchMin: 0.85,
    pitchMax: 1.0,
    factionTags: [FactionAudioId.ORC],
  },
  'combat.tower_attack.splash.human': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.35),
    category: SoundCategory.COMBAT,
    cooldownMs: C(80),
    pitchMin: 0.85,
    pitchMax: 1.0,
    factionTags: [FactionAudioId.HUMAN],
  },
  'combat.tower_attack.splash.elf': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.35),
    category: SoundCategory.COMBAT,
    cooldownMs: C(80),
    pitchMin: 0.85,
    pitchMax: 1.0,
    factionTags: [FactionAudioId.ELF],
  },
  'combat.creep_hit': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.22),
    category: SoundCategory.COMBAT,
    cooldownMs: C(80),
    pitchMin: 0.95,
    pitchMax: 1.05,
    maxDurationSec: 0.2,
  },
  'combat.creep_death.basic': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.32),
    category: SoundCategory.COMBAT,
    cooldownMs: C(100),
    pitchMin: 0.8,
    pitchMax: 1.0,
    maxDurationSec: 0.35,
  },
  'combat.creep_death.elite': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.4),
    category: SoundCategory.COMBAT,
    cooldownMs: C(150),
    pitchMin: 0.7,
    pitchMax: 0.9,
    maxDurationSec: 0.5,
  },
  'combat.creep_escape': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.35),
    category: SoundCategory.COMBAT,
    pitchMin: 0.8,
    pitchMax: 0.95,
    maxDurationSec: 0.4,
  },
  'combat.invalid_build': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.3),
    category: SoundCategory.COMBAT,
    pitchMin: 0.6,
    pitchMax: 0.75,
    maxDurationSec: 0.25,
  },
  'combat.successful_build': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.3),
    category: SoundCategory.COMBAT,
    pitchMin: 1.1,
    pitchMax: 1.2,
    maxDurationSec: 0.35,
  },
  'combat.sell_tower': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.28),
    category: SoundCategory.COMBAT,
    maxDurationSec: 0.3,
  },
  'ambient.map': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.15),
    category: SoundCategory.AMBIENT,
    loop: true,
  },
  'ambient.tension': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.12),
    category: SoundCategory.AMBIENT,
    loop: true,
  },
  'ambient.faction.undead': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.18),
    category: SoundCategory.AMBIENT,
    loop: true,
    factionTags: [FactionAudioId.UNDEAD],
  },
  'ambient.faction.orc': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.18),
    category: SoundCategory.AMBIENT,
    loop: true,
    factionTags: [FactionAudioId.ORC],
  },
  'ambient.faction.human': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.18),
    category: SoundCategory.AMBIENT,
    loop: true,
    factionTags: [FactionAudioId.HUMAN],
  },
  'ambient.faction.elf': {
    ...DEFAULT_SOUND_CONFIG,
    volume: V(0.18),
    category: SoundCategory.AMBIENT,
    loop: true,
    factionTags: [FactionAudioId.ELF],
  },
};

export const SOUND_ASSET_PATHS: Record<SoundId, string> = {
  'ui.click': 'assets/audio/sfx/ui/ui_click_01.wav',
  'ui.hover': 'assets/audio/sfx/ui/ui_hover_01.wav',
  'ui.open': 'assets/audio/sfx/ui/ui_open_01.wav',
  'ui.close': 'assets/audio/sfx/ui/ui_close_01.wav',
  'ui.error': 'assets/audio/sfx/ui/ui_error_01.wav',
  'ui.success': 'assets/audio/sfx/ui/ui_success_01.wav',
  'ui.build_select': 'assets/audio/sfx/ui/ui_build_select_01.wav',
  'ui.faction_select': 'assets/audio/sfx/ui/ui_faction_select_01.wav',
  'ui.wave_start': 'assets/audio/sfx/ui/ui_wave_start_01.wav',
  'ui.wave_complete': 'assets/audio/sfx/ui/ui_wave_complete_01.wav',
  'ui.game_over': 'assets/audio/sfx/ui/ui_game_over_01.wav',
  'ui.victory': 'assets/audio/sfx/ui/ui_victory_01.wav',
  'system.pause': 'assets/audio/sfx/system/system_pause_01.wav',
  'system.unpause': 'assets/audio/sfx/system/system_unpause_01.wav',
  'system.restart': 'assets/audio/sfx/system/system_restart_01.wav',
  'economy.gold_gain': 'assets/audio/sfx/economy/economy_gold_gain_01.wav',
  'economy.gold_spent': 'assets/audio/sfx/economy/economy_gold_spent_01.wav',
  'economy.refund': 'assets/audio/sfx/economy/economy_refund_01.wav',
  'economy.life_lost': 'assets/audio/sfx/economy/economy_life_lost_01.wav',
  'economy.wave_reward': 'assets/audio/sfx/economy/economy_wave_reward_01.wav',
  'combat.tower_attack.archer': 'assets/audio/sfx/combat/combat_archer_attack_01.wav',
  'combat.tower_attack.archer.undead': 'assets/audio/sfx/combat/combat_archer_attack_01.wav',
  'combat.tower_attack.archer.orc': 'assets/audio/sfx/combat/combat_archer_attack_01.wav',
  'combat.tower_attack.archer.human': 'assets/audio/sfx/combat/combat_archer_attack_01.wav',
  'combat.tower_attack.archer.elf': 'assets/audio/sfx/combat/combat_archer_attack_01.wav',
  'combat.tower_attack.splash': 'assets/audio/sfx/combat/combat_splash_attack_01.wav',
  'combat.tower_attack.splash.undead': 'assets/audio/sfx/combat/combat_splash_attack_01.wav',
  'combat.tower_attack.splash.orc': 'assets/audio/sfx/combat/combat_splash_attack_01.wav',
  'combat.tower_attack.splash.human': 'assets/audio/sfx/combat/combat_splash_attack_01.wav',
  'combat.tower_attack.splash.elf': 'assets/audio/sfx/combat/combat_splash_attack_01.wav',
  'combat.creep_hit': 'assets/audio/sfx/combat/combat_archer_attack_01.wav',
  'combat.creep_death.basic': 'assets/audio/sfx/combat/combat_splash_attack_01.wav',
  'combat.creep_death.elite': 'assets/audio/sfx/combat/combat_splash_attack_01.wav',
  'combat.creep_escape': 'assets/audio/sfx/ui/ui_error_01.wav',
  'combat.invalid_build': 'assets/audio/sfx/ui/ui_error_01.wav',
  'combat.successful_build': 'assets/audio/sfx/ui/ui_success_01.wav',
  'combat.sell_tower': 'assets/audio/sfx/economy/economy_refund_01.wav',
  'ambient.map': 'assets/audio/sfx/ambient/ambient_map_01.wav',
  'ambient.tension': 'assets/audio/sfx/ambient/ambient_tension_01.wav',
  'ambient.faction.undead': 'assets/audio/sfx/ambient/ambient_map_01.wav',
  'ambient.faction.orc': 'assets/audio/sfx/ambient/ambient_map_01.wav',
  'ambient.faction.human': 'assets/audio/sfx/ambient/ambient_map_01.wav',
  'ambient.faction.elf': 'assets/audio/sfx/ambient/ambient_map_01.wav',
};

export const AUDIO_CONSTANTS = {
  MAX_SIMULTANEOUS_SOUNDS: 12,
  MAX_SIMULTANEOUS_SAME_CATEGORY: 6,
  DEFAULT_MASTER_VOLUME: 0.7,
  MOBILE_UNLOCK_DEBOUNCE_MS: 500,
  CLEANUP_CHECK_INTERVAL_MS: 500,
  POOL_SIZE: 8,
} as const;
