export enum TowerCombatConfig {
  ARCHER_RANGE_CELLS = 3,
  ARCHER_DAMAGE = 20,
  ARCHER_ATTACK_COOLDOWN_MS = 800,
  SPLASH_RANGE_CELLS = 2.5,
  SPLASH_DAMAGE = 18,
  SPLASH_ATTACK_COOLDOWN_MS = 1200,
  SPLASH_RADIUS_CELLS = 1.5,
}
