export enum TowerCombatConfig {
  ARCHER_RANGE_CELLS = 3,
  ARCHER_DAMAGE = 20,
  ARCHER_ATTACK_COOLDOWN_MS = 800,
  SPLASH_RANGE_CELLS = 2,
  SPLASH_DAMAGE = 15,
  SPLASH_ATTACK_COOLDOWN_MS = 1200,
}
